import {advanceForward,caughtForward,crossingError,TARGET_DEPTH} from './physics.js';
import {createPicnic} from './scene3d.js';
import {newRun,reward,miss,tick,wave} from './arcade.js';
import {courses,gap,resolveCourse,targetHeight} from './courses.js';
const $=id=>document.getElementById(id), canvas=$('arena'), view=createPicnic(canvas);
const levels=[{title:'Lunch is served',name:'Bear',art:'brown_bear',hello:'Bear saved you a seat.',done:'One happy bear.'},{title:'Meals on wheels',name:'Dog',art:'doggo',hello:'Dog likes lunch on the go.',done:'Special delivery. Woof!'},{title:'Hop to it',name:'Frog',art:'froggo',hello:'Frog is hopping hungry.',done:'The whole crew is fed!'}];
let W=900,H=540,level=0,score=0,clock=0,ball=null,drag=null,particles=[],cooldown=0,last=0,paused=false,win=false,successPulse=0,portraitMode=null,started=false,manualPause=false,hitStop=0,trail=[],audio=null,soundOn=true,keyboardAim=0;
let lostSnacks=[],perfectCatch=false,aimVoice=null;
let run=newRun(),pendingWave=0,popUntil=0,bannerUntil=0,best=0;
try{best=Math.max(0,Number(localStorage.getItem('snack-break-best'))||0);}catch{}
$('personal-best').textContent='Your best: '+best.toLocaleString();
const launch=()=>view.project({x:0,h:.7,z:0},W,H);
function target(t){const difficulty=wave(run),speed=1+Math.min(.75,(difficulty-1)*.08);return {x:level===1?(difficulty>4?Math.sin(t*.85*speed)*.25:0):(difficulty>3?Math.sin(t*.8*speed)*(level===0?1.2:.8):0),h:targetHeight(level)+(level===2?Math.max(0,Math.sin(t*1.45*speed))*.65:0),z:TARGET_DEPTH,radiusX:Math.max(.5,.85-(difficulty-1)*.035),radiusH:Math.max(.28,.42-(difficulty-1)*.018)};}
function hoop(t){return {x:level===1?1.4:(level===2?gap(t).x:target(t).x*.45+(wave(run)>1?Math.sin(t*.65)*.35:0)),h:1.35+Math.sin(t*.8)*.10,z:3,radiusX:.4,radiusH:.3};}
function opening(t){const p=view.project(target(t),W,H);return {...p,width:target(t).radiusX*200*p.scale};}
function setMessage(text){$('reaction').textContent=text;}
function updateScore(){[...$('deliveries').children].forEach((el,i)=>el.classList.toggle('filled',i<run.lives));$('deliveries').setAttribute('aria-label',run.lives+' chances remaining');$('points').textContent=run.points.toLocaleString();$('combo').textContent=run.streak?'×'+Math.min(4,1+Math.floor((run.streak-1)/3))+' · '+run.streak+' STREAK':'BUILD A COMBO';$('timer').textContent=Math.ceil(run.remaining)+'s';$('timer').classList.toggle('urgent',run.remaining<=10);}
function startRun(){lostSnacks=[];stopAimSound();run=newRun();clock=0;pendingWave=0;popUntil=0;bannerUntil=0;$('wave-banner').hidden=true;$('shot-pop').className='';$('angle').value=55;$('power').value=64;$('angle').oninput();$('power').oninput();setLevel(0);$('hint').textContent=courses[0].hint;$('hint').style.opacity='1';}
function endRun(){if(win)return;stopAimSound();win=true;ball=null;drag=null;pendingWave=0;const newBest=run.points>best;best=Math.max(best,run.points);try{localStorage.setItem('snack-break-best',String(best));}catch{}$('personal-best').textContent='Your best: '+best.toLocaleString();$('complete-label').textContent=newBest?'NEW PERSONAL BEST!':run.lives<=0?'OUT OF SNACKS!':'PICNIC COMPLETE';$('complete-title').textContent=run.points.toLocaleString()+' points';$('complete-copy').textContent=newBest?'The crew will be talking about this picnic.':'One more picnic?';$('run-stats').textContent=run.hits+' catches · '+run.perfects+' perfects · '+run.rings+' hoops · '+run.banks+' banks · Best streak '+run.bestStreak;$('next').textContent='One more round ↻';$('celebration').hidden=false;tone(520,.2);}
function setLevel(n){stopAimSound();level=n;score=0;keyboardAim=0;pendingWave=0;ball=null;drag=null;particles=[];cooldown=0;win=false;$('celebration').hidden=true;$('level').value=n;$('level-number').textContent='ROUND '+String(wave(run)).padStart(2,'0');$('level-title').textContent=courses[n].name;$('hint').textContent=courses[n].hint;$('hint').style.opacity='1';setMessage(levels[n%3].hello);updateScore();$('throw').disabled=false;}
function velocity(){const pull=drag?Math.max(20,Math.min(110,drag.now.y-drag.start.y)):65;const vz=drag?pull/65*6:Number($('power').value)/64*6;const aim=drag?Math.max(-3,Math.min(3,-(drag.now.x-drag.start.x)/pull*vz*.55)):keyboardAim;return {vx:aim,vz,vh:Math.tan(Number($('angle').value)*Math.PI/180)*vz*.298};}
function shoot(){if(!started||manualPause||ball||win||cooldown>0||pendingWave)return;stopAimSound();run.active=true;const v=velocity();ball={x:0,z:0,h:.7,...v,age:0,rotation:0};trail=[];tone(460,.09);$('hint').style.opacity='0';drag=null;$('throw').disabled=true;setMessage(['Oooooh…','Come to papa!','Snack incoming!'][level%3]);}
function finishShot(hit,error){const gold=ball?.golden,bank=ball?.banked;if(!hit&&ball){lostSnacks.push({...ball,vx:ball.vx*.45,vz:error?.blocked?-1.2:ball.vz*.3,life:0,settled:false});lostSnacks=lostSnacks.slice(-3);}ball=null;cooldown=hit?.32:.5;if(hit){const perfect=Math.abs(error.x)<.22&&Math.abs(error.h)<.16;const earned=reward(run,{perfect,ring:gold,bank});score++;perfectCatch=perfect;successPulse=1;view.catchSnack({perfect,bank});hitStop=.06;tone(perfect?880:660,.13);setTimeout(()=>tone(1100,.12),95);updateScore();const o=opening(clock);for(let i=0;i<(gold?28:18);i++)particles.push({x:o.x,y:o.y,vx:(Math.random()-.5)*220,vy:-70-Math.random()*170,life:1,color:['#efac66','#fff8cc','#7a9d62'][i%3]});setMessage(bank?'That bank shot! AGAIN!':perfect?'Right in the sweet spot!':gold?'A snack AND a trick shot?!':'NOM! Keep them coming!');$('shot-pop').textContent=(bank?'BANK SHOT! ':perfect?'PERFECT! ':gold?'TRICK SHOT! ':'')+'+'+earned;$('shot-pop').className='show'+(gold?' gold':'');popUntil=clock+1.1;if(run.hits%3===0){pendingWave=clock+.6;$('wave-banner').textContent='Round '+(wave(run))+' · '+courses[(level+1)%courses.length].name;$('wave-banner').hidden=false;bannerUntil=clock+1.6;}}else{miss(run);updateScore();setMessage(error?.message||['The ants say thanks.','Floor picnic, apparently.','Still hungry over here!'][Math.floor(Math.random()*3)]);$('shot-pop').textContent='COMBO DROPPED';$('shot-pop').className='show miss';popUntil=clock+.8;tone(190,.12);if(run.finished)endRun();}}
function resize(){stopAimSound();const r=canvas.getBoundingClientRect(),portrait=r.width/r.height<1.2;W=portrait?520:900;H=W*r.height/r.width;if(portraitMode!==portrait){portraitMode=portrait;$('power').value=64;$('power-value').textContent='64%';}view.resize();ball=null;drag=null;$('throw').disabled=win;}
new ResizeObserver(resize).observe(canvas);
function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};}
canvas.addEventListener('pointerdown',e=>{if(!started||manualPause||ball||win||cooldown>0)return;const p=point(e),s=launch();if(Math.hypot(p.x-s.x,p.y-s.y)>65)return;drag={id:e.pointerId,start:p,now:p};canvas.setPointerCapture(e.pointerId);startAimSound();setMessage('Pull back toward you. Release!');});
canvas.addEventListener('pointermove',e=>{if(drag?.id===e.pointerId){drag.now=point(e);updateAimSound();}});
canvas.addEventListener('pointerup',e=>{if(drag?.id!==e.pointerId)return;if(Math.hypot(drag.start.x-drag.now.x,drag.start.y-drag.now.y)<8){drag=null;stopAimSound();return;}shoot();});
canvas.addEventListener('pointercancel',()=>{drag=null;stopAimSound();});canvas.addEventListener('lostpointercapture',()=>drag=null);
$('throw').onclick=()=>{manualPause=false;$('pause-screen').hidden=true;shoot();};$('reset').onclick=()=>{startRun();manualPause=false;$('pause-screen').hidden=true;};$('next').onclick=()=>{startRun();canvas.focus();};$('level').onchange=e=>setLevel(Number(e.target.value));
for(const id of ['angle','power'])$(id).oninput=()=>$(id+'-value').textContent=$(id).value+(id==='angle'?'°':'%');
document.addEventListener('visibilitychange',()=>{paused=document.hidden;last=0;drag=null;stopAimSound();});
function draw(dt){const t=target(clock),head=view.project({x:t.x+.95,h:t.h+1.9,z:7.5},W,H);$('reaction').style.left=(head.x/W*100)+'%';$('reaction').style.top=(Math.max(H*.20,head.y)/H*100)+'%';const trajectory=[];if(drag){let p={x:0,z:0,h:.7,...velocity(),age:0};for(let i=0;i<28;i++){const next=resolveCourse(p,advanceForward(p,.045),level,clock+i*.045,clock+(i+1)*.045);p=next.ball;trajectory.push(p);if(next.blocked||p.h<0||p.z>6.3)break;}}const pull=drag?{x:(drag.now.x-drag.start.x)*.003,h:.7-(drag.now.y-drag.start.y)*.002,z:-Math.max(0,drag.now.y-drag.start.y)*.006}:null;view.render({level,time:clock,target:t,ring:hoop(clock),ball,pulse:successPulse,aim:!!drag,pull,trajectory,history:trail,dt,perfect:perfectCatch,lostSnacks,showSnack:!ball&&!win&&cooldown===0});}
function simulate(dt){if(hitStop>0)hitStop=Math.max(0,hitStop-dt);if(!paused&&!manualPause&&started&&!win&&hitStop===0){const before=target(clock),ringBefore=hoop(clock);clock+=dt;if(run.finished)endRun();if(pendingWave&&clock>=pendingWave){const nextLevel=(level+1)%3;setLevel(nextLevel);cooldown=.3;}if(popUntil&&clock>=popUntil){$('shot-pop').className='';popUntil=0;}if(!pendingWave&&clock>=bannerUntil)$('wave-banner').hidden=true;const after=target(clock),ringAfter=hoop(clock);if(ball&&!win){const prev=ball;trail.push({...ball});if(trail.length>7)trail.shift();const interaction=resolveCourse(prev,advanceForward(ball,dt),level,clock-dt,clock);ball=interaction.ball;ball.rotation=prev.rotation+dt*5;if(interaction.impact){view.impact(interaction.impact);if(interaction.impact.type==='board')woodTok();else tone(interaction.impact.type==='mushroom'?760:420,.14);}if(interaction.blocked)finishShot(false,interaction);else {if(!ball.golden&&caughtForward(prev,ball,ringBefore,ringAfter)){ball.golden=true;tone(1200,.08);}if(caughtForward(prev,ball,before,after))finishShot(true,crossingError(prev,ball,before,after));else if(ball.z>=TARGET_DEPTH)finishShot(false);else if(ball.h<0){if(ball.vh<-1&&ball.age<2){ball.h=0;ball.vh*=-.28;ball.vz*=.65;}else finishShot(false);}else if(ball.age>4)finishShot(false);}} cooldown=Math.max(0,cooldown-dt);if(!ball&&!cooldown&&!win&&!pendingWave)$('throw').disabled=false;}if(!paused&&!manualPause){lostSnacks=lostSnacks.filter(p=>{p.life+=dt;if(!p.settled){Object.assign(p,advanceForward(p,dt));p.rotation+=dt*5;if(p.h<.12){p.h=.12;if(p.vh<-1){p.vh*=-.3;p.vz*=.6;p.vx*=.6;}else{p.settled=true;p.vh=0;}}}else{p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-dt*3);p.vz*=Math.exp(-dt*3);if(p.life>2.4)p.x+=dt*.35;}return p.life<6;});successPulse=Math.max(0,successPulse-dt*1.25);}particles=particles.filter(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=300*dt;p.life-=dt;return p.life>0;});}
function frame(now){const rawDt=last?Math.max(0,(now-last)/1000):0;last=now;const active=started&&!paused&&!manualPause&&!win;if(active)tick(run,Math.min(rawDt,1));let remaining=Math.min(rawDt,.5);while(remaining>0){const step=Math.min(remaining,1/60);simulate(step);remaining-=step;}updateScore();draw(paused||manualPause?0:Math.min(rawDt,.1));requestAnimationFrame(frame);}

function snackPosition(){const s=launch();if(!drag)return s;return {x:s.x+Math.max(-65,Math.min(30,(drag.now.x-drag.start.x)*.3)),y:s.y+Math.max(-30,Math.min(65,(drag.now.y-drag.start.y)*.3))};}
function tone(freq,length){if(!soundOn||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*.7,audio.currentTime+length);gain.gain.setValueAtTime(.055,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+length);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+length);}
function unlockAudio(){try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{soundOn=false;}}
$('play').onclick=()=>{startRun();started=true;document.body.classList.remove('menu');$('title-screen').hidden=true;unlockAudio();tone(520,.12);canvas.focus();};
$('sound').setAttribute('aria-pressed','true');$('sound').setAttribute('aria-label','Mute sound');
$('sound').onclick=()=>{soundOn=!soundOn;if(soundOn)unlockAudio();else stopAimSound();$('sound').setAttribute('aria-pressed',soundOn);$('sound').setAttribute('aria-label',soundOn?'Mute sound':'Enable sound');};
$('pause').onclick=()=>{if(!started)return;manualPause=!manualPause;$('pause-screen').hidden=!manualPause;drag=null;stopAimSound();};
$('resume').onclick=()=>{manualPause=false;$('pause-screen').hidden=true;canvas.focus();};
document.addEventListener('keydown',e=>{if(!started||manualPause||['INPUT','SELECT','BUTTON','A','SUMMARY'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();shoot();}const adjustment={ArrowLeft:['angle',0],ArrowRight:['angle',0],ArrowUp:['power',2],ArrowDown:['power',-2]}[e.key];if(adjustment){e.preventDefault();if(e.key==='ArrowLeft')keyboardAim=Math.max(-3,keyboardAim-.15);if(e.key==='ArrowRight')keyboardAim=Math.min(3,keyboardAim+.15);const el=$(adjustment[0]);el.value=Math.min(+el.max,Math.max(+el.min,+el.value+adjustment[1]));el.oninput();$('hint').textContent='Aim '+keyboardAim.toFixed(1)+' · Power '+$('power').value+'% · Space to throw';$('hint').style.opacity='1';}});
$('level').replaceChildren(...courses.map((course,i)=>{const option=document.createElement('option');option.value=i;option.textContent=course.name;return option;}));
document.body.classList.add('menu');setLevel(0);requestAnimationFrame(frame);





$('play').disabled=true;$('play').textContent='Setting the picnic…';view.ready.then(()=>{$('play').disabled=false;$('play').textContent="Let's snack! ▸";}).catch(error=>{console.error(error);$('play').textContent='Crew unavailable — reload to retry';});

function stopAimSound(){if(!aimVoice)return;const voice=aimVoice;aimVoice=null;voice.gain.gain.cancelScheduledValues(audio.currentTime);voice.gain.gain.setTargetAtTime(.0001,audio.currentTime,.025);voice.osc.stop(audio.currentTime+.15);}
function startAimSound(){stopAimSound();if(!soundOn||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';gain.gain.value=.008;osc.connect(gain);gain.connect(audio.destination);osc.start();aimVoice={osc,gain};updateAimSound();}
function updateAimSound(){if(!aimVoice||!drag)return;const power=Math.max(0,Math.min(110,drag.now.y-drag.start.y))/110;aimVoice.osc.frequency.setTargetAtTime(160+power*360,audio.currentTime,.06);aimVoice.gain.gain.setTargetAtTime(.008+power*.012,audio.currentTime,.06);}
function woodTok(){if(!audio||!soundOn)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(280,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(80,audio.currentTime+.09);gain.gain.setValueAtTime(.11,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.11);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.12);}
